### ISSUE TITLE
Overpaid tippin

### ISSUE THREAD

**Issue by Engelberg** [instagibbs/CoreFeeHelper#3]
To experiment with lightning, I intended to send a small tip of 450 sats as a token of appreciation for your service. My wallet app mistakenly interpreted this as $450 even though I clearly entered it as sats, converted that dollar amount to bitcoin, and sent it on without ever asking me to confirm, which really sucks (I won't be using BlueWallet ever again!) I know you have no obligation to return the extra funds, but it was a mistake. Would you be so kind as to get in touch with me to return the funds?

**Comment by Engelberg** [comment]
(The tipped amount, specifically, was 0.00803662 BTC).

I do want to tip you, but this was not the right amount.

**Comment by instagibbs** [comment]
Emailed you :+1:
